version: "3"
services:
  postgres:
    build: .
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=random_data
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./data:/data
    command:
      - postgres
      - -c
      - log_statement=all
      - -c
      - log_destination=stderr
