[tool.pytest.ini_options]
minversion = "7.0"
addopts = ". -vvv -ra"
testpaths = ["test"]
log_level = "INFO"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_file = "test_server.log"
console_output_style = "count"
faulthandler_timeout = 60


[tool.black]
line_length = 88
extend-exclude = "venv"

[tool.isort]
profile = "black"
force_single_line = true
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
